// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase.options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNQOheSfA2H_mzjn_F9-DGfESh23VQug',
    appId: '1:363358399676:web:a5a310e60cd278dcc9b4b9',
    messagingSenderId: '363358399676',
    projectId: 'ye-quotes',
    authDomain: 'ye-quotes.firebaseapp.com',
    storageBucket: 'ye-quotes.appspot.com',
    measurementId: 'G-FGG4ERJSEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbu6li9qsGvLGmuxy5K8nkKBnW3xRR24',
    appId: '1:363358399676:android:c7df718b816fb0b6c9b4b9',
    messagingSenderId: '363358399676',
    projectId: 'ye-quotes',
    storageBucket: 'ye-quotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbqVIrw3yuLmKDxlMm975AX91a4OlaLs',
    appId: '1:363358399676:ios:24a2f76ddb7ca2a7c9b4b9',
    messagingSenderId: '363358399676',
    projectId: 'ye-quotes',
    storageBucket: 'ye-quotes.appspot.com',
    iosClientId: '363358399676-694d5vgp83gsnpf10vpr5j6tacnanjef.apps.googleusercontent.com',
    iosBundleId: 'com.example.yePhrases',
  );
}
